name: Gentx Signatures
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  verify-signatures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: gentx-validation
        run: |
          git clone https://github.com/cosmos-gaminghub/nibiru
          cd nibiru
          make install
          cd ../
          bash -x ./scripts/generate-genesis.sh
